### ISSUE TITLE
wireframe meus eventos 

### ISSUE THREAD

**Issue by pabloRodrigo1** [SoapPablo/Projeto-Mobile#17]

**Comment by ArthurYamamotoo** [comment]
![Image](https://github.com/SoapPablo/Projeto-Mobile/assets/128550901/54121359-8f7d-4cb7-9873-9518e1413763)


![Image](https://github.com/SoapPablo/Projeto-Mobile/assets/128550901/699541ba-aaf3-420b-bcee-637f5b70bc03)



![Image](https://github.com/SoapPablo/Projeto-Mobile/assets/128550901/e4190e01-5cbc-4b76-86a7-e84f6b18f7d6)



![Image](https://github.com/SoapPablo/Projeto-Mobile/assets/128550901/50b961da-9db8-4893-9359-0cd8c4c9212b)
