### ISSUE TITLE
wireframe pagina descrição do evento 

### ISSUE THREAD

**Issue by pabloRodrigo1** [SoapPablo/Projeto-Mobile#25]

**Comment by ArthurYamamotoo** [comment]
![Image](https://github.com/SoapPablo/Projeto-Mobile/assets/128550901/8350ef8d-d61e-42bf-bfed-d5ffd30e3392)



![Image](https://github.com/SoapPablo/Projeto-Mobile/assets/128550901/17debd82-9283-419e-b702-bbb28e9aa31a)
